CREATE DATABASE CUSTOMER
USE CUSTOMER

-- 1 What is the total revenue generated by male vs female customer
select gender,sum(purchase_amount) as Revenue
from customers
group by gender

-- 2 WHich customers used  discount bill but still spent more than the average purchase amount
select customer_id,purchase_amount from customers where discount_applied ='Yes' 
and purchase_amount >(select avg(purchase_amount) from customers)

-- Q3 Which are the top 5 products with highest review rating?
select item_purchased As Product,round(avg(review_rating),2) As "Average Review Rating" from customers 
group by item_purchased
order by avg(review_rating) desc limit 5

-- Q4 Compare the average purchase amount between standard and Express Shipping
select shipping_type,round(avg(purchase_amount),2) from customers
where shipping_type in('Express','Standard')
group by shipping_type

-- Q5 Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscribers
select subscription_status, count(customer_id) As Total_Customers,
round(avg(purchase_amount),2) As "Average Revenue",
round(sum(purchase_amount),2) As "Total Revenue"
from customers
where subscription_status in ('Yes', 'No')
group by subscription_status

-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/ count(*),2) As Dicount_rate
from customers
group by item_purchased
order by Dicount_rate desc
limit 5

-- Q7 Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show the count of each segment and the revenue 
-- generated
WITH customer_type AS (SELECT customer_id,previous_purchases,purchase_amount,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customers)
SELECT customer_segment,COUNT(*) AS number_of_customers,SUM(purchase_amount) AS total_revenue
FROM customer_type
GROUP BY customer_segment
ORDER BY total_revenue DESC;


-- Q8 What are the top 3 most purchased products within each category
with item_counts as (select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category,item_purchased)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3

-- Q9 Are customers who are repeat buyers( more than 5 previous purchases) also likesly to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customers
where previous_purchases>5
group by subscription_status

-- Q10 What is the revenue contribution of each age group
select age_group, sum(purchase_amount) As Revenue_Contribution
from customers
group by age_group
order by Revenue_Contribution desc





















